FROM docker.io/rust:latest

# Install dependencies for Tauri (WebKitGTK, etc.) and Node.js
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential libwebkit2gtk-4.1-dev libssl-dev libgtk-3-dev \
    libayatana-appindicator3-dev librsvg2-dev pkg-config file \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

# Install Tauri CLI
RUN cargo install tauri-cli --locked --version "^2.0"

WORKDIR /usr/src/osaima-shell

# Copy source files
COPY package.json .
COPY index.html .
COPY src ./src
COPY src-tauri ./src-tauri

# Install npm dependencies and build the UI
RUN npm install && cargo tauri build --release
