FROM docker.io/rust:latest

WORKDIR /usr/src/mcp-daemon

COPY Cargo.toml .
COPY src ./src

# Install pkg-config and libssl-dev which might be needed for some sysinfo/tokio dependencies on linux
RUN apt-get update && apt-get install -y pkg-config libssl-dev

RUN cargo check
RUN cargo build --release

CMD ["./target/release/mcp-daemon"]
